#!/bin/bash  
### BEGIN INIT INFO
# Provides:          radiusconfig
# Required-Start:    
# Required-Stop:
# Default-Start:     
# Default-Stop:
# Short-Description: radiusconfig.
# Description:       radiusconfig.
### END INIT INFO
# Source function library  
. /lib/lsb/init-functions

# start function  
start() { 

export PGPASSWORD=$pg_pass
echo "psql --host=$pg_host --username=$pg_user --port=$pg_port --database=$pg_dbase --port=$pg_port";

cat /etc/freeradius/3.0/mods-available/i9_sql  \
    |  sed -e "s/#pg_port/$pg_port/g" \
    | sed -e "s/#pg_user/$pg_user/g" \
    | sed -e "s/#pg_pass/$pg_pass/g" \
    | sed -e "s/#pg_dbase/$pg_dbase/g" \
    | sed -e "s/#pg_host/$pg_host/g" \
    > /etc/freeradius/3.0/mods-available/sql

echo "CREATE DATABASE \"$pg_dbase\" WITH OWNER \"$pg_user\";" > /usr/src/raddb/setup.sql

CREATE_DB=`psql --host=$pg_host --username=$pg_user --port=$pg_port --command="SELECT datname FROM pg_database" | grep "$pg_dbase" | wc -l`
if [ "$CREATE_DB" -lt "1" ]; 
  then
        psql --host=$pg_host --username=$pg_user --port=$pg_port --dbname=$pg_dbase --file=/usr/src/raddb/setup.sql
        psql --host=$pg_host --username=$pg_user --port=$pg_port --dbname=$pg_dbase --file=/usr/src/raddb/schema.sql
        psql --host=$pg_host --username=$pg_user --port=$pg_port --dbname=$pg_dbase --file=/usr/src/raddb/ippool.sql
        psql --host=$pg_host --username=$pg_user --port=$pg_port --dbname=$pg_dbase --file=/usr/src/raddb/cui.sql
fi

echo "radius database connection via postgres is set up"
}  
 
case "$1" in  
start)  
  start  
  ;;  
stop)   
  ;;  
reload|restart)   
  ;;  
status)   
  ;;  
*)  
  echo $"Usage: $0 {start|stop|restart|status}"  
  exit 1  
esac