#!/bin/bash  
### BEGIN INIT INFO
# Provides:          radius-config
# Required-Start:    
# Required-Stop:
# Default-Start:     
# Default-Stop:
# Short-Description: radius-config.
# Description:       radius-config.
### END INIT INFO
# Source function library  
. /lib/lsb/init-functions

# start function  
start() { 

export PGPASSWORD=$PG_PASS

cat /etc/freeradius/3.0/mods-available/i9_sql  \
    |  sed -e "s/#pg_port/$PG_PORT/g" \
    | sed -e "s/#pg_user/$PG_USER/g" \
    | sed -e "s/#pg_pass/$PG_PASS/g" \
    | sed -e "s/#pg_dbase/$PG_DBASE/g" \
    | sed -e "s/#pg_host/$PG_HOST/g" \
    > /etc/freeradius/3.0/mods-available/sql

echo "CREATE DATABASE \"$PG_DBASE\" WITH OWNER \"$PG_USER\";" > /usr/src/raddb/setup.sql

CREATE_DB=`psql --host=$PG_HOST --username=$PG_USER --port=$PG_PORT --command="SELECT datname FROM pg_database" | grep "$PG_DBASE" | wc -l`
if [ "$CREATE_DB" -lt "1" ]; 
  then
        psql --host=$PG_HOST --username=$PG_USER --port=$PG_PORT --dbname=$PG_DBASE --file=/usr/src/raddb/setup.sql
        psql --host=$PG_HOST --username=$PG_USER --port=$PG_PORT --dbname=$PG_DBASE --file=/usr/src/raddb/schema.sql
        psql --host=$PG_HOST --username=$PG_USER --port=$PG_PORT --dbname=$PG_DBASE --file=/usr/src/raddb/ippool.sql
        psql --host=$PG_HOST --username=$PG_USER --port=$PG_PORT --dbname=$PG_DBASE --file=/usr/src/raddb/cui.sql
fi

echo "radius database connection via postgres is set up"
}  
 
case "$1" in  
start)  
  start  
  ;;  
stop)   
  ;;  
reload|restart)   
  ;;  
status)   
  ;;  
*)  
  echo $"Usage: $0 {start|stop|restart|status}"  
  exit 1  
esac